name: Conditional Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: exit 1  # Симулируем неудачное выполнение

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: failure()  # Выполнять job2 только в случае неудачи job1
    steps:
      - name: Step 1
        run: echo "This is Job 2"

  job3:
    runs-on: ubuntu-latest
    needs: job1
    if: success()  # Выполнять job3 только в случае успеха job1
    steps:
      - name: Step 1
        run: echo "This is Job 3"
        
