name: My Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is Job 1"
      - name: Step 2
        run: exit 1  # Симулируем неправильное завершение

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: failure()  # Выполнять job2 только в случае неудачи job1
    steps:
      - name: Confirm Retry
        id: confirm_retry
        run: |
          echo "Job 1 failed. Do you want to retry Job 2?"
          echo "::set-output name=retry::$(read)"
      - name: Retry Job 2
        if: steps.confirm_retry.outputs.retry == 'yes'
        run: echo "Retrying Job 2"
        
