name: Interactive Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is Job 1"

  choose_job:
    runs-on: ubuntu-latest
    needs: job1
    if: always()
    steps:
      - name: Select Job
        id: select_job
        run: |
          echo "Choose which job to run next:"
          echo "1. Job 2"
          echo "2. Job 3"
          echo "::set-env name=SELECTED_JOB::$(read)"
      - name: Run Selected Job
        if: env.SELECTED_JOB == '1'
        run: echo "Running Job 2"
      - name: Run Selected Job
        if: env.SELECTED_JOB == '2'
        run: echo "Running Job 3"
        
