name: Interactive Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is Job 1"

  choose_job:
    runs-on: ubuntu-latest
    needs: job1
    if: always()
    steps:
      - name: Select Job
        run: |
          echo "Choose which job to run next:"
          echo "1. Job 2"
          echo "2. Job 3"
          echo "SELECTED_JOB=$(read)" >> $GITHUB_ENV
      - name: Run Selected Job
        run: |
          if [ "$SELECTED_JOB" == "1" ]; then
            echo "Running Job 2"
          elif [ "$SELECTED_JOB" == "2" ]; then
            echo "Running Job 3"
          else
            echo "Invalid selection: $SELECTED_JOB"
            exit 1
          fi
          
